name: Update LinkedIn Posts

on:
  schedule:
    - cron: "0 6 * * *"   # joka päivä klo 06 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install playwright
      - run: playwright install chromium
      - run: python scraper.py
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add posts/
          git commit -m "Update LinkedIn posts" || echo "No new posts"
          git push
